export const faculty = [
  {
    imageSrc: "nadeemIqbal.jpg",
    name: { title: "Dr. ", fullName: "NADEEM IQBAL" },
    designation: "Head Of The Department",
    academicTitle: "Prof",
    role: "Head Of The Department",
    education: "Ph.D.",
    email: "nikhan@awkum.edu.pk",
  },
  {
    imageSrc: "MAQSOODHAYAT.jpg",
    name: { title: "Dr. ", fullName: " MAQSOOD HAYAT" },
    designation: " Prof/Controller of Examination",
    academicTitle: "Prof",
    role: "Controller of Examination",
    education: "Ph.D. ",
    email: "m.hayat@awkum.edu.pk",
  },
  {
    imageSrc: "RAHIMKHAN.jpg",
    name: { title: "Dr. ", fullName: "RAHIM KHAN" },
    designation: "Associate Prof/QEC Coordinator",
    academicTitle: "Associate Prof",
    role: "QEC Coordinator",
    education: "Ph.D.",
    email: "rahimkhan@awkum.edu.pk",
  },

  {
    imageSrc: "HASHIMALI.png",
    name: { title: "Dr. ", fullName: "HASHIM ALI" },
    designation: "Assistant Professor/BS Coordinator",
    academicTitle: "Assistant Professor",
    role: "BS Coordinator",
    education: "Ph.D.",
    email: "hashimali@awkum.edu.pk",
  },
  {
    imageSrc: "FAZLULLAHKHAN.jpg",
    name: { title: "Dr. ", fullName: "FAZLULLAH KHAN" },
    designation: "Assistant Professor & MS/Ph.D Coordinator",
    academicTitle: "Assistant Professor",
    role: "MS/Ph.D Coordinator",
    education: "Ph.D.",
    email: "fazlullah@awkum.edu.pk",
  },

  {
    imageSrc: "AFTABAHMED.jpg",
    name: { title: "Dr. ", fullName: "AFTAB AHMED" },
    designation: "Lecturer/NECAC Coordinator",
    academicTitle: "Lecturer",
    role: "NECAC Coordinator",
    education: "Ph.D.",
    email: "aftab.ahmed.khan@awkum.edu.pk",
  },
  {
    imageSrc: "salman.jpg",
    name: { title: "Dr. ", fullName: "SALMAN" },
    designation: "Lecturer/BS Coordinator",
    academicTitle: "Lecturer",
    role: "BS Coordinator",
    education: "Ph.D.",
    email: "salman@awkum.edu.pk",
  },
  {
    imageSrc: "AAMIRAKBAR.jpg",
    name: { title: "Dr. ", fullName: "AAMIR AKBAR" },
    designation: "Lecturer/FYP Coordinator",
    academicTitle: "Lecturer",
    role: "FYP Coordinator",
    education: "Ph.D.",
    email: "amirakbar@awkum.edu.pk",
  },
];
// {
//   imageSrc: "SHAHZADKHAN.jpg",
//   name: { title: "Mr.", fullName: "SHAHZAD KHAN" },
//   designation: "Lecturer",
//   education: "",
//   email: "shahzad@awkum.edu.pk",
// },

// {
//   imageSrc: "ROOHULLAHJANSYED.jpg",
//   name: { title: "Dr.", fullName: "ROOHULLAH JAN SYED" },
//   designation: "Lecturer",
//   education: "Ph.D.",
//   email: "roohullahsyed@awkum.edu.pk",
// },
// {
//   imageSrc: "MIANAHMADJAN.jpg",
//   name: { title: "Dr.", fullName: "MIAN AHMAD JAN" },
//   designation: "Assistant Professor",
//   education: "Ph.D.",
//   email: "mianjan@awkum.edu.pk",
// },
// {
//   imageSrc: "SHERAFZALKHAN.jpg",
//   name: { title: "Dr.", fullName: "SHER AFZAL KHAN" },
//   designation: "Professor",
//   education: "Ph.D.",
//   email: "sher.afzal@awkum.edu.pk",
// },
// {
//   imageSrc: "MUHAMMADTAHIR.jpg",
//   name: { title: "Dr.", fullName: "MUHAMMAD TAHIR" },
//   designation: "Assistant Professor",
//   education: "Ph.D.",
//   email: "muhammadtahir@awkum.edu.pk",
// },
